# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    ".idea",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "mock_content_hub",
]

# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
select = ["E", "F", "CPY", "FA102", "I"]

ignore = [
    "COM812",  # The formatter enforces consistent use of trailing commas, making the rule redundant
    "D203",  # incorrect-blank-line-before-class
    "D213",  # multi-line-summary-second-line
    "D100",  # undocumented-public-module
    "D101",  # undocumented-public-class
    "D104",  # undocumented-public-package
    "D105",  # undocumented-magic-method
    "D107",  # undocumented-public-init
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "I"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

preview = true

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks, and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

preview = true

[lint.per-file-ignores]
"**/[Tt]ests/**" = [
    "S101",
    "ARG",
    "FBT",
    "PLR2004",
    "S311",
    "D",
    "DOC",
    "PLR6301",
    "PLC1901",
]
"**/response_integrations/**" = [
    "TID252",
]
"**/response_integrations/third_party/**" = [
    "CPY",
]

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10