creator: Rob
default_result_value: ''
description: This action will cause the current playbook to pause until all playbooks
    from the previous alert complete.
dynamic_results_metadata:
-   result_example_path: null
    result_name: JsonResult
    show_result: true
integration_identifier: Tools
is_async: true
name: Lock Playbook
parameters: []
script_result_name: ScriptResult
