creator: 464c66fb-e0db-48d9-8c72-d2a408bb425d
default_result_value: ''
description: Search a specified string within the records of an environment's custom
    list. (If no values are provided will return all custom lists records)
dynamic_results_metadata:
-   result_example_path: resources/SearchEnvironmentCustomLists_JsonResult_example.json
    result_name: JsonResult
    show_result: true
integration_identifier: Lists
name: Search Environment Custom Lists
parameters:
-   default_value: ''
    description: String to search within list values
    is_mandatory: false
    name: String to Search
    type: string
-   default_value: ''
    description: Comma separated values
    is_mandatory: false
    name: Categories
    type: string
script_result_name: Match_Records
