name: Build Marketplace Integrations
permissions:
  contents: read
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  mp_build:
    name: Build Marketplace
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Build all integrations
      shell: bash
      run: |
        mp config --root-path . --processes 10 --display-config
        mp build --repository third_party --repository commercial