name: Test Marketplace Integrations

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  run-tests:
    name: Run Tests On PR Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp

    - name: Run integration tests
      env:
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        mp config --root-path . --processes 10 --display-config
        mp test --repository third_party --repository commercial --raise-error-on-violations

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: ./artifacts/test_report.md
        retention-days: 2