name: Windows Workflows
permissions:
  contents: read
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  mp_build_windows:
    name: Build Marketplace on windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Build all integrations
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp build --repository third_party --repository commercial

  test_mp_windows:
    name: Test mp Package on windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: 'latest'
        python-version: '3.11'

    - name: Create venv
      working-directory: packages/mp
      run: |
        uv sync --dev

    - name: Run pytest
      working-directory: packages/mp
      run: |
        .venv\Scripts\pytest.exe tests -n 10 --cov

  validate_windows:
    name: Run Validation On PR Code on windows
    runs-on: windows-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp

    - name: Run Validations
      env:
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        PYTHONIOENCODING: "utf-8"
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp validate --repository third_party --only-pre-build

  run-tests-windows:
    name: Run Tests On PR Code on windows
    runs-on: windows-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./packages/mp

    - name: Run integration tests
      env:
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
      shell: pwsh
      run: |
        wmp config --root-path . --processes 10 --display-config
        wmp test --repository third_party --repository commercial --raise-error-on-violations